name: Remote SSH Command
on: [push]
jobs:
  Remote-SSH-Command:
    name: Construire le projet
    runs-on: ubuntu-latest
    steps:
      
name: Récupérer le code
      uses: actions/checkout@v4

      
name: Transférer les fichiers via SCP
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sudo apt-get install -y sshpass
        mkdir -p ~/.ssh
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        sshpass -p "$SSH_PASSWORD" scp addition.py $SSH_USER@$SSH_HOST:/home/ubuntu/YubaR/